spring:
    datasource: 
        url: jdbc:postgresql://localhost:5432/authentication
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    error:
        include-message: always
    url: http://192.168.8.100:8080