INSERT INTO degree(name) VALUES
('Bachelor of Science in Information Technology (General)'),
('Bachelor of Science in Information Technology (Special)'),
('Postgraduate Diploma in Information Technology'),
('Master of Science in Information Technology'),
('Postgraduate Diploma in Information System'),
('Master of Science in Information Systems'),
('Postgraduate Diploma in Information Management'),
('Master of Science in Information Management'),
('Bachelor of Business Administration (Special), (Honours)'),
('Bachelor of Science of Engineering in Mechanical Engineering'),
('Bachelor of Science of Engineering in Civil Engineering'),
('Bachelor of Science of Engineering in Materials Engineering'),
('Master of Philosophy in Information Technology'),
('Master of Philosophy in Software Engineering'),
('Master of Philosophy in Computer Networks'),
('Master of Philosophy in Cyber Security'),
('Master of Philosophy in Civil Engineering'),
('Master of Philosophy in Electrical and Electronics Engineering'),
('Master of Philosophy in Mechanical Engineering'),
('Master of Philosophy in Materials Engineering'),
('Doctor of Philosophy in Information Technology'),
('Doctor of Philosophy in Software Engineering'),
('Doctor of Philosophy in Computer Network'),
('Doctor of Philosophy in Cyber Security'),
('Doctor of Philosophy in Electrical and Electronics Engineering'),
('Postgraduate Diploma in Computer Networks'),
('Postgraduate Diploma in Project Management'),
('Postgraduate Diploma in Industrial Management'),
('Postgraduate Diploma in Human Resource Management'),
('Postgraduate Diploma in Business Management')