INSERT INTO job_title(name) VALUES
('Computer technician'),
('Computer support technician'),
('IT technician'),
('Operations analyst'),
('Systems designer'),
('Senior systems analyst'),
('Application support analyst'),
('Systems analyst'),
('Solutions architect'),
('Web designer'),
('Web engineer'),
('Web development manager'),
('Web development project manager'),
('User experience (UX) designer'),
('User interface (UI) designer'),
('UX/UI researcher'),
('UX/UI specialist'),
('Multimedia architect'),
('Web analytics developer'),
('Interaction designer'),
('Front-end designer'),
('Front-end developer'),
('Mobile developer'),
('Full-stack developer'),
('Technology manager'),
('Technology specialist'),
('IT sales executive'),
('Business systems analyst'),
('Security specialist'),
('IT security analyst'),
('Network security engineer'),
('Information security analyst'),
('Information security engineer'),
('Information security manager'),
('Information security consultant'),
('Information security project manager'),
('Information security program manager'),
('Management information director'),
('Cyber security specialist'),
('Cyber security manager'),
('Database developer'),
('Database analyst'),
('Database manager'),
('Database engineer'),
('Software Engineer'),
('Network administrator'),
('Network architect')