INSERT INTO institute(name, location) VALUES
('University of Colombo', 'Sri Lanka'),
('University of Peradeniya', 'Sri Lanka'),
('University of Sri Jayewardenepura', 'Sri Lanka'),
('University of Kelaniya', 'Sri Lanka'),
('University of Moratuwa', 'Sri Lanka'),
('University of Jaffna', 'Sri Lanka'),
('University of Ruhuna', 'Sri Lanka'),
('The Open University of Sri Lanka', 'Sri Lanka'),
('Eastern University, Sri Lanka', 'Sri Lanka'),
('South Eastern University of Sri Lanka', 'Sri Lanka'),
('Rajarata University of Sri Lanka', 'Sri Lanka'),
('Sabaragamuwa University of Sri Lanka', 'Sri Lanka'),
('Wayamba University of Sri Lanka', 'Sri Lanka'),
('Uva Wellassa University of Sri Lanka', 'Sri Lanka'),
('University of the Visual & Performing Arts', 'Sri Lanka'),
('Sri Lanka Institute of Information Technology (Guarantee) Limited', 'Sri Lanka'),
('Aquinas College of Higher Studies', 'Sri Lanka'),
('South Asian Institute of Technology and Medicine Ltd', 'Sri Lanka'),
('National School of Business Management Limited (NSBM)', 'Sri Lanka'),
('Horizon College of Businee & Technology (pvt) Ltd', 'Sri Lanka'),
('SLT Campus (pvt) Ltd', 'Sri Lanka');